### ISSUE TITLE
inconsistent handling of ticker - should be forced to upper case as in company_valuation.py

### ISSUE THREAD

**Issue by dabrown645** [razorhash/pyfmpcloud#4]
company_valuation.py does a ticker.upper() bit crypto.py, stock_time_series.py, and forex.py do not. This should be consistent and I think it should be to uppercase ticker if it was not submitted as company_valuation.py does

**Comment by dabrown645** [comment]
I know the python to fix this. I can try to figure out the github work flow to submit fix.

**Comment by razorhash** [comment]
The API handles the capitalizations internally so this will not make or break anything. 
You can submit a pull request for this cosmetic change if you'd like to work on it. 

https://opensource.com/article/19/7/create-pull-request-github

Let me know if that helps

**Comment by razorhash** [comment]
closed with release v1.1.6
